<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
        
        <meta name="robots" content="noindex, noarchive">
        <meta name="googlebot" content="noindex, noarchive, nosnippet, noodp">
	
	<title>oups ! erreur | <?php echo $v_code; ?> - <?php echo $v_title; ?></title>

	<style type="text/css"><?php echo $css; ?></style>
</head>

<body>

	<div class="cover">
		<h1><?php echo $v_title; ?> <small>Error <?php echo $v_code; ?></small></h1>
		<p class="lead"><?php echo $v_message; ?></p>
	</div>
	
	<?php if ($config['footer'] != null){ ?>
	<footer>
		<p><?php echo $config['footer']; ?></p>
	</footer>
	<?php } ?>
	
</body>
</html>
